# Site settings
title: ARWHD
email: charlespeters42@gmail.com
description: "As I struggle through working as a web designer, I find myself, missing the mark, aiming but not always making contact. I thought the best way to move forward was to share the mistakes and the successes, to have them set alongside the good ideas, best practices and summations of what I know. This site is meant to be a good place to discuss those things like Design, User Experience, Front-end Development and Client Services, that I find challenging and make some sense of them."
baseurl: ""
url: "http://arwhd.co"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["node_modules", "package.json"]
