---
title: ARWHD
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: charlespeters42@gmail.com
old-description: As I struggle through working as a web designer, I find myself, missing
  the mark, aiming but not always making contact. I thought the best way to move forward
  was to share the mistakes and the successes, to have them set alongside the good
  ideas, best practices and summations of what I know. This site is meant to be a
  good place to discuss those things like Design, User Experience, Front-end Development
  and Client Services, that I find challenging and make some sense of them.
description: |
  A blog about design, front-end development and hitting your targets.
baseurl: ''
url: http://arwhd.co
gems:
- jekyll-paginate
paginate: 3
paginate_path: blog/page:num
markdown: kramdown
permalink: pretty

collections:
  links:
    output: true
    permalink: /links/:path/

exclude: ["Session.vim","checklist.md", "README.md", "node_modules", "paths.js", "package.json", "Gulpfile.babel.js", "assets/src/"]
